### ISSUE TITLE
Update initialization function now that eth-connector is merged

### ISSUE THREAD

**Issue by birchmd** [aurora-is-near/aurora.js#2]
The [`initialize` function](https://github.com/aurora-is-near/aurora.js/blob/50e82721a1015d93cc0732f9abfec3fca6a610cd/src/engine.ts#L144) currently only calls the `new` method for the contract. However, on a fresh deploy that is not enough; the `new_eth_connector` contract method needs to be called to initialize the Eth-connector, otherwise other contract calls will return an error (e.g. this is causing problems in the bully now: https://github.com/aurora-is-near/aurora-engine/issues/122#issuecomment-865438367 ).

This issue is to update `initialize` to include a call to `new_eth_connector` as well. This can still involve a single NEAR transaction (if desired) by including multiple function call actions in one transaction.

This change will also need to be bubbled up to `aurora-cli` (which depends on this package).

**Comment by artob** [comment]
@birchmd I merged, but we should really sort out in the Engine why we have two separate initialization calls, it's not a good state of affairs. Also, yes, these should definitely be called atomically in the same transaction, if we can figure out how to do that. (Feel free to take a stab at it.)

**Comment by birchmd** [comment]
> @birchmd I merged, but we should really sort out in the Engine why we have two separate initialization calls, it's not a good state of affairs.

Yes, I totally agree. I pointed this out in a comment while the eth-connector was being developed: https://github.com/aurora-is-near/aurora-engine/pull/71#discussion_r630315041 but I guess it must have been lost in the shuffle of trying to ship. I've filed https://github.com/aurora-is-near/aurora-engine/issues/161 to take care of this.
