### ISSUE TITLE
Make sure to index all transactions affecting the state

### ISSUE THREAD

**Issue by mfornet** [aurora-is-near/aurora.js#23]
Transactions are filtered by those that affect the EVM [here](https://github.com/aurora-is-near/aurora.js/blob/master/src/transaction.ts#L48). The function `raw_call` doesn't exist, and probably it refers to [`call`](https://github.com/aurora-is-near/aurora-engine/blob/master/engine/src/lib.rs#L194).

To be able to reproduce exactly the same state we have on-chain with the indexed data, all txs that affects the EVM state should be indexed. Notice that there are functions that modify Aurora contract state but not the EVM state. Those don't need to be necessarily indexed.

- [`new`](https://github.com/aurora-is-near/aurora-engine/blob/master/engine/src/lib.rs#L100)
- [`deploy_code`](https://github.com/aurora-is-near/aurora-engine/blob/master/engine/src/lib.rs#L183)
- [`call`](https://github.com/aurora-is-near/aurora-engine/blob/master/engine/src/lib.rs#L194)
- [`submit`](https://github.com/aurora-is-near/aurora-engine/blob/master/engine/src/lib.rs#L206)
- [`meta_call`](https://github.com/aurora-is-near/aurora-engine/blob/master/engine/src/lib.rs#L308)
- [`ft_on_transfer`](https://github.com/aurora-is-near/aurora-engine/blob/master/engine/src/lib.rs#L352)
- [`deploy_erc20_token`](https://github.com/aurora-is-near/aurora-engine/blob/master/engine/src/lib.rs#L370)
- [`withdraw`](https://github.com/aurora-is-near/aurora-engine/blob/master/engine/src/lib.rs#L510)
- [`deposit`](https://github.com/aurora-is-near/aurora-engine/blob/master/engine/src/lib.rs#L515)
- [`finish_deposit`](https://github.com/aurora-is-near/aurora-engine/blob/master/engine/src/lib.rs#L520)
- [`ft_transfer`](https://github.com/aurora-is-near/aurora-engine/blob/master/engine/src/lib.rs#L559)
- [`ft_resolve_transfer`](https://github.com/aurora-is-near/aurora-engine/blob/master/engine/src/lib.rs#L564)
- [`ft_transfer_call`](https://github.com/aurora-is-near/aurora-engine/blob/master/engine/src/lib.rs#L569)

**Comment by spilin** [comment]
This repository is no longer maintained.
