### ISSUE TITLE
Error -32603 when sending transactions to mainnet from metamask

### ISSUE THREAD

**Issue by oliverhamilton7915** [aurora-is-near/aurora.js#31]
Hey all, I am getting the following error (`{code: -32603, message: Error: Exception(None,)`} when sending a transaction from metamask to RPC node `https://mainnet.aurora.dev` ...any tips on how to fix this? It seems like an RPC error. Is there another public RPC node I can connect to?

**Comment by spilin** [comment]
This repository is no longer maintained.
